# 전처리

이제 되는 거냐구~! 어이!

In [64]:
print('hello, world')

hello, world

In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import math
import platform

df = pd.read_csv(r'C:\Users\컴퓨터\Documents\[부캠][basic] 심화프로젝트\2025_Airbnb_NYC_listings.csv') #----- 자기 경로 설정!!

In [66]:
df_host = df[['host_id','host_name','host_since','host_location','host_response_time','host_response_rate','host_acceptance_rate','host_is_superhost','host_listings_count','host_identity_verified']]
df_host

,host_id,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_identity_verified
0,62165,Michael,2009-12-11,"New York, NY",NaN,NaN,NaN,f,1.0,t
1,157798,Irene,2010-07-04,"New York, NY",NaN,NaN,100%,f,1.0,t
2,165789,Sarah,2010-07-13,"New York, NY",within a few hours,100%,40%,f,1.0,t
3,166532,Matthew,2010-07-14,"New York, NY",within an hour,100%,97%,t,1.0,t
4,168525,Gustavo,2010-07-16,"New York, NY",within an hour,100%,100%,t,2.0,t
...,...,...,...,...,...,...,...,...,...,...
22303,40019013,Cecilia,2015-07-30,"New York, NY",NaN,NaN,NaN,f,1.0,t
22304,483056418,Kristina,2022-10-10,"New York, NY",within an hour,100%,80%,t,24.0,t
22305,30283594,Global Luxury Suites,2015-03-30,"Hawthorne, NJ",within an hour,94%,99%,f,619.0,t
22306,407304997,Boomerang,2021-06-15,"New York, NY",within an hour,89%,100%,f,26.0,t
22307,483056418,Kristina,2022-10-10,"New York, NY",within an hour,100%,80%,t,24.0,t

In [67]:
df_lct = df[['neighbourhood','neighbourhood_group_cleansed','latitude','longitude']]
df_lct

,neighbourhood,neighbourhood_group_cleansed,latitude,longitude
0,Neighborhood highlights,Brooklyn,40.673760,-73.966110
1,Neighborhood highlights,Manhattan,40.792454,-73.940742
2,Neighborhood highlights,Brooklyn,40.684420,-73.980680
3,Neighborhood highlights,Manhattan,40.818058,-73.946671
4,Neighborhood highlights,Brooklyn,40.710651,-73.950874
...,...,...,...,...
22303,NaN,Manhattan,40.813794,-73.952399
22304,NaN,Brooklyn,40.685500,-73.919510
22305,NaN,Manhattan,40.745290,-73.979380
22306,NaN,Manhattan,40.757133,-73.983124
22307,NaN,Brooklyn,40.685500,-73.919510

In [68]:
df_info = df[['property_type','room_type','accommodates','bedrooms','beds','bathrooms','amenities']]
df_info

,property_type,room_type,accommodates,bedrooms,beds,bathrooms,amenities
0,Private room in rental unit,Private room,1,1.0,1.0,1.0,"[""Refrigerator"", ""Dishes and silverware"", ""Wif..."
1,Private room in condo,Private room,2,1.0,1.0,1.0,"[""Oven"", ""Blender"", ""Luggage dropoff allowed"",..."
2,Private room in home,Private room,2,5.0,5.0,2.5,"[""Portable fans"", ""Oven"", ""Baking sheet"", ""Fir..."
3,Entire home,Entire home/apt,2,1.0,1.0,1.0,"[""Fire extinguisher"", ""Clothing storage: close..."
4,Private room in rental unit,Private room,2,1.0,1.0,1.0,"[""Oven"", ""Rice maker"", ""Laundromat nearby"", ""L..."
...,...,...,...,...,...,...,...
22303,Private room in rental unit,Private room,1,1.0,1.0,1.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ..."
22304,Private room in rental unit,Private room,2,1.0,0.0,1.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ..."
22305,Entire rental unit,Entire home/apt,5,2.0,3.0,2.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ..."
22306,Entire rental unit,Entire home/apt,4,2.0,2.0,1.0,"[""Oven"", ""Gym"", ""Blender"", ""Dedicated workspac..."
22307,Private room in rental unit,Private room,2,1.0,0.0,1.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ..."

In [69]:
df_price = df[['price','minimum_nights','maximum_nights','availability_365','instant_bookable']]
df_price

,price,minimum_nights,maximum_nights,availability_365,instant_bookable
0,$200.00,90,365,362,f
1,$82.00,30,999,204,f
2,$765.00,3,60,326,f
3,$139.00,2,45,25,f
4,$130.00,4,45,38,f
...,...,...,...,...,...
22303,$72.00,30,365,358,f
22304,$58.00,30,365,363,f
22305,$299.00,30,365,99,f
22306,$200.00,30,365,365,t
22307,$58.00,30,365,363,f

In [70]:
df_review = df[['number_of_reviews','reviews_per_month','review_scores_rating','review_scores_cleanliness','review_scores_communication','first_review','last_review']]
df_review

,number_of_reviews,reviews_per_month,review_scores_rating,review_scores_cleanliness,review_scores_communication,first_review,last_review
0,9,0.05,4.88,4.80,5.00,2010-12-11,2013-05-10
1,102,0.58,4.77,4.76,4.90,2010-10-04,2023-12-09
2,43,0.28,4.70,4.52,4.88,2012-07-09,2023-08-30
3,241,1.36,4.85,4.50,4.96,2010-08-28,2025-02-21
4,274,1.54,4.82,4.61,4.88,2010-08-02,2025-01-03
...,...,...,...,...,...,...,...
22303,0,NaN,NaN,NaN,NaN,NaN,NaN
22304,0,NaN,NaN,NaN,NaN,NaN,NaN
22305,0,NaN,NaN,NaN,NaN,NaN,NaN
22306,0,NaN,NaN,NaN,NaN,NaN,NaN
22307,0,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
df_notion = df[['host_id','host_name','host_since','host_location','host_response_time','host_response_rate','host_acceptance_rate','host_is_superhost','host_listings_count','host_identity_verified',
                'neighbourhood','neighbourhood_group_cleansed','latitude','longitude',
                'property_type','room_type','accommodates','bedrooms','beds','bathrooms','amenities',
                'price','minimum_nights','maximum_nights','availability_365','instant_bookable',
                'number_of_reviews','reviews_per_month','review_scores_rating','review_scores_cleanliness','review_scores_communication','first_review','last_review']]
df_notion

,host_id,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_identity_verified,...,maximum_nights,availability_365,instant_bookable,number_of_reviews,reviews_per_month,review_scores_rating,review_scores_cleanliness,review_scores_communication,first_review,last_review
0,62165,Michael,2009-12-11,"New York, NY",NaN,NaN,NaN,f,1.0,t,...,365,362,f,9,0.05,4.88,4.80,5.00,2010-12-11,2013-05-10
1,157798,Irene,2010-07-04,"New York, NY",NaN,NaN,100%,f,1.0,t,...,999,204,f,102,0.58,4.77,4.76,4.90,2010-10-04,2023-12-09
2,165789,Sarah,2010-07-13,"New York, NY",within a few hours,100%,40%,f,1.0,t,...,60,326,f,43,0.28,4.70,4.52,4.88,2012-07-09,2023-08-30
3,166532,Matthew,2010-07-14,"New York, NY",within an hour,100%,97%,t,1.0,t,...,45,25,f,241,1.36,4.85,4.50,4.96,2010-08-28,2025-02-21
4,168525,Gustavo,2010-07-16,"New York, NY",within an hour,100%,100%,t,2.0,t,...,45,38,f,274,1.54,4.82,4.61,4.88,2010-08-02,2025-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22303,40019013,Cecilia,2015-07-30,"New York, NY",NaN,NaN,NaN,f,1.0,t,...,365,358,f,0,NaN,NaN,NaN,NaN,NaN,NaN
22304,483056418,Kristina,2022-10-10,"New York, NY",within an hour,100%,80%,t,24.0,t,...,365,363,f,0,NaN,NaN,NaN,NaN,NaN,NaN
22305,30283594,Global Luxury Suites,2015-03-30,"Hawthorne, NJ",within an hour,94%,99%,f,619.0,t,...,365,99,f,0,NaN,NaN,NaN,NaN,NaN,NaN
22306,407304997,Boomerang,2021-06-15,"New York, NY",within an hour,89%,100%,f,26.0,t,...,365,365,t,0,NaN,NaN,NaN,NaN,NaN,NaN
22307,483056418,Kristina,2022-10-10,"New York, NY",within an hour,100%,80%,t,24.0,t,...,365,363,f,0,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
df_notion.head()

,host_id,host_name,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_identity_verified,...,maximum_nights,availability_365,instant_bookable,number_of_reviews,reviews_per_month,review_scores_rating,review_scores_cleanliness,review_scores_communication,first_review,last_review
0,62165,Michael,2009-12-11,"New York, NY",NaN,NaN,NaN,f,1.0,t,...,365,362,f,9,0.05,4.88,4.80,5.00,2010-12-11,2013-05-10
1,157798,Irene,2010-07-04,"New York, NY",NaN,NaN,100%,f,1.0,t,...,999,204,f,102,0.58,4.77,4.76,4.90,2010-10-04,2023-12-09
2,165789,Sarah,2010-07-13,"New York, NY",within a few hours,100%,40%,f,1.0,t,...,60,326,f,43,0.28,4.70,4.52,4.88,2012-07-09,2023-08-30
3,166532,Matthew,2010-07-14,"New York, NY",within an hour,100%,97%,t,1.0,t,...,45,25,f,241,1.36,4.85,4.50,4.96,2010-08-28,2025-02-21
4,168525,Gustavo,2010-07-16,"New York, NY",within an hour,100%,100%,t,2.0,t,...,45,38,f,274,1.54,4.82,4.61,4.88,2010-08-02,2025-01-03

In [73]:
df_notion.head(7).T

,0,1,2,3,4,5,6
host_id,62165,157798,165789,166532,168525,169927,15991
host_name,Michael,Irene,Sarah,Matthew,Gustavo,Hubert,Allen & Irina
host_since,2009-12-11,2010-07-04,2010-07-13,2010-07-14,2010-07-16,2010-07-17,2009-05-06
host_location,"New York, NY","New York, NY","New York, NY","New York, NY","New York, NY","Saint-Aubin-sur-Scie, France","New York, NY"
host_response_time,NaN,NaN,within a few hours,within an hour,within an hour,NaN,within an hour
host_response_rate,NaN,NaN,100%,100%,100%,NaN,100%
host_acceptance_rate,NaN,100%,40%,97%,100%,NaN,100%
host_is_superhost,f,f,f,t,t,f,t
host_listings_count,1.0,1.0,1.0,1.0,2.0,2.0,1.0
host_identity_verified,t,t,t,t,t,t,t
neighbourhood,Neighborhood highlights,Neighborhood highlights,Neighborhood highlights,Neighborhood highlights,Neighborhood highlights,NaN,NaN
neighbourhood_group_cleansed,Brooklyn,Manhattan,Brooklyn,Manhattan,Brooklyn,Manhattan,Brooklyn
latitude,40.67376,40.792454,40.68442,40.818058,40.710651,40.76203,40.70935
longitude,-73.96611,-73.940742,-73.98068,-73.946671,-73.950874,-73.98869,-73.95342
property_type,Private room in rental unit,Private room in condo,Private room in home,Entire home,Private room in rental unit,Private room in rental unit,Entire rental unit
room_type,Private room,Private room,Private room,Entire home/apt,Private room,Private room,Entire home/apt
accommodates,1,2,2,2,2,2,3
bedrooms,1.0,1.0,5.0,1.0,1.0,1.0,2.0
beds,1.0,1.0,5.0,1.0,1.0,1.0,1.0
bathrooms,1.0,1.0,2.5,1.0,1.0,NaN,1.0
amenities,"[""Refrigerator"", ""Dishes and silverware"", ""Wif...","[""Oven"", ""Blender"", ""Luggage dropoff allowed"",...","[""Portable fans"", ""Oven"", ""Baking sheet"", ""Fir...","[""Fire extinguisher"", ""Clothing storage: close...","[""Oven"", ""Rice maker"", ""Laundromat nearby"", ""L...","[""Kitchen"", ""Air conditioning"", ""Dishes and si...","[""Oven"", ""Fire extinguisher"", ""Extra pillows a..."
price,$200.00,$82.00,$765.00,$139.00,$130.00,$139.00,$96.00
minimum_nights,90,30,3,2,4,30,30
maximum_nights,365,999,60,45,45,1125,120
availability_365,362,204,326,25,38,365,173
instant_bookable,f,f,f,f,f,f,f
number_of_reviews,9,102,43,241,274,44,194
reviews_per_month,0.05,0.58,0.28,1.36,1.54,0.25,1.01
review_scores_rating,4.88,4.77,4.7,4.85,4.82,4.86,4.58
review_scores_cleanliness,4.8,4.76,4.52,4.5,4.61,4.83,4.85
review_scores_communication,5.0,4.9,4.88,4.96,4.88,5.0,4.8
first_review,2010-12-11,2010-10-04,2012-07-09,2010-08-28,2010-08-02,2010-08-31,2009-05-25
last_review,2013-05-10,2023-12-09,2023-08-30,2025-02-21,2025-01-03,2019-01-03,2024-10-05

In [110]:
df_info.info()

<class 'pandas.DataFrame'>
RangeIndex: 22308 entries, 0 to 22307
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  22308 non-null  str
 1   room_type      22308 non-null  str
 2   accommodates   22308 non-null  int64
 3   bedrooms       22259 non-null  float64
 4   beds           22229 non-null  float64
 5   bathrooms      22302 non-null  float64
 6   amenities      22308 non-null  str
dtypes: float64(3), int64(1), str(3)
memory usage: 1.2 MB

In [111]:
df['room_type'].value_counts(dropna=False)

room_type
Entire home/apt    12664
Private room        9186
Hotel room           372
Shared room           86
Name: count, dtype: int64

In [112]:
df_info['room_type'].isna().sum()

np.int64(0)

In [ ]:
df_info.loc[df_info['host_listings_count'].isna()]

,Unnamed: 0,id,source,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
229,355,302758,city scrape,Sunny 1BR East Harlem Apartment,Two-room apartment in East Harlem. Close to su...,"Ethnic diversity, proximity to subway and buse...",8605,NaN,NaN,NaN,...,4.75,3.83,4.17,NaN,f,1,1,0,0,0.08
1452,3528,7037918,city scrape,"Near LGA, Citifield, US Open Tennis","Comfortable, sunny, cozy bedroom in private ho...",We live in a quiet residential neighborhood ne...,36242220,NaN,NaN,NaN,...,4.93,4.87,4.76,NaN,f,1,0,1,0,1.97
2943,8944,20193830,city scrape,Family brownstone with backyard,"Located in Clinton Hill, a historic Brooklyn n...",NaN,1294005,NaN,NaN,NaN,...,4.98,4.96,4.88,OSE-STRREG-0000992,f,1,1,0,0,1.24
3161,9561,21802923,city scrape,Private Bedroom with Private Entrance in Brook...,You will have a large bedroom with a private e...,My personal faves in the area.<br /><br />Coff...,72466752,NaN,NaN,NaN,...,4.80,4.85,4.65,NaN,f,1,0,1,0,0.61
6090,16572,45189535,city scrape,Private Room for Sleeping in Great Neighborhood,"Safe, quiet, private, NYC room available just ...",One of the Best neighborhoods in Manhattan! Cl...,364960386,NaN,NaN,NaN,...,4.92,4.96,4.92,NaN,f,1,0,1,0,0.49
6536,17341,47009616,city scrape,1 bedroom apartment near Staten Island ferry,This is a one bedroom apartment with a living ...,10 minute buss ride to Staten Island ferry 20 ...,260396179,NaN,NaN,NaN,...,4.71,4.58,4.71,NaN,f,4,4,0,0,0.51
6568,17398,46705156,city scrape,2 Bedroom apartment in ENY Business District,Cozy 2BR APARTMENT with huge master BR and wal...,Location in the East Brooklyn Business distric...,377484768,NaN,NaN,NaN,...,4.86,4.18,4.69,NaN,f,1,1,0,0,2.16
7354,18705,49980221,city scrape,2 bedroom apartment near Staten Island ferry,This is a two bedroom apartment near the State...,718 tre nine fiv 0to1four,260396179,NaN,NaN,NaN,...,4.96,4.57,4.71,NaN,f,4,4,0,0,0.76
8307,20106,53050810,city scrape,Bedroom w/private bathroom in Unit2 in Greenpoint,"Greenpoint is a safe, convenient option for ex...",Greenpoint is a super walkable neighborhood wi...,17888612,NaN,NaN,NaN,...,4.99,4.95,4.93,OSE-STRREG-0000212,f,1,0,1,0,4.30
11373,24325,736139385311072356,city scrape,Relaxing 1 Bedroom in Brooklyn,"Unwind in this cute, modern, 1 bedroom apartme...",Bay ridge is brooklyns best hidden neighborhoo...,35174210,NaN,NaN,NaN,...,5.00,5.00,4.83,NaN,f,2,2,0,0,0.32
12242,25466,794381586846683007,city scrape,Stunning 1 family home 5BR/2.5 All new!,"Kick back and relax in this calm, stylish spac...","While residential and quiet, Crown Heights off...",117540494,NaN,NaN,NaN,...,4.25,4.67,4.42,NaN,f,1,1,0,0,0.52
13424,26989,868140563222071942,city scrape,Penthouse walking to Best of NYC,Enjoy this sunny south facing centrally-locate...,NaN,50402335,NaN,NaN,NaN,...,5.00,5.00,5.00,NaN,t,1,1,0,0,0.07
13928,27648,888426985116704427,city scrape,One bedroom apartment,This is a one bedroom apartment with a living ...,NaN,260396179,NaN,NaN,NaN,...,4.75,4.25,4.25,NaN,f,4,4,0,0,0.37
14258,28086,911059653094636598,city scrape,Flatbush 2 Rooms,This stylish place to stay is perfect for grou...,NaN,219152877,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
14412,28309,922665961458727772,city scrape,Apartment in Crown Heights,Welcome to my charming and spacious apartment ...,NaN,229592691,NaN,NaN,NaN,...,5.00,5.00,5.00,NaN,f,1,1,0,0,0.13
15380,29443,982833752250568153,city scrape,Comfortable Brownstone Retreat,Spacious tasteful designer brownstone suite we...,NaN,220765580,NaN,NaN,NaN,...,5.00,4.83,4.91,OSE-STRREG-0002142,f,1,0,1,0,3.79
15758,29893,1007480104408240518,city scrape,The perfect Brooklyn 1 bedroom,Welcome to your private 1<br />bed 1 bath in t...,NaN,40744019,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
19045,33845,1181394579984036414,city scrape,A cozy apartment near Yankee Stadium,"We are a 20min drive from LGA Airport, and 15m...",NaN,252043685,NaN,NaN,NaN,...,5.00,4.64,4.91,OSE-STRREG-0002450,t,1,0,1,0,1.90
19421,34306,1212347649197198907,city scrape,Newly Renovated APT - Near ALL,Keep it simple at this peaceful and centrally-...,NaN,593138234,NaN,NaN,NaN,...,4.50,4.50,4.50,NaN,f,1,1,0,0,0.32
20749,35815,1294847782653168909,city scrape,2 bed 2 bath in BedStuy,2 bedroom 2 bathroom in the heart of Bedford S...,NaN,130148524,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,t,1,1,0,0,NaN

In [78]:
df_super = df.loc[df['host_is_superhost'] == 't']
df_normal = df.loc[df['host_is_superhost'] == 'f']

In [79]:
df_normal['review_scores_rating'].mean()

np.float64(4.652157002858309)

In [80]:
df_super['host_listings_count'].mean()

np.float64(22.42323380649372)

## TOP 10 amenities 출력

In [84]:
import ast
from collections import Counter

# 1. 문자열(String) 형태를 진짜 리스트(List)로 변환
# 데이터가 "['Wifi', 'Heating']" 처럼 따옴표까지 포함된 글자라면 이 과정이 꼭 필요!!
df['amenities'] = df['amenities'].apply(ast.literal_eval)

# 2. 리스트를 개별 행으로 펼치기 (Explode)
# 한 칸에 들어있던 [A, B, C]를 각각 3개의 행(A / B / C)으로 쪼개줍니다.
exploded_amenities = df['amenities'].explode()

# 3. 개수 세고 상위 10개 추출
top_10_amenities = exploded_amenities.value_counts().head(10)

In [87]:
top_10_amenities

amenities
Smoke alarm              21096
Wifi                     20577
Carbon monoxide alarm    19386
Kitchen                  19122
Hot water                17333
Essentials               16548
Hangers                  16524
Hair dryer               15354
Iron                     15268
Air conditioning         14922
Name: count, dtype: int64

In [85]:
exploded_amenities

0                 Refrigerator
0        Dishes and silverware
0                         Wifi
0                      Kitchen
0                     Elevator
                 ...
22307                   Washer
22307                     Wifi
22307              Smoke alarm
22307                  Kitchen
22307                       TV
Name: amenities, Length: 684508, dtype: str

In [86]:
df['amenities']

0        [Refrigerator, Dishes and silverware, Wifi, Ki...
1        [Oven, Blender, Luggage dropoff allowed, Dedic...
2        [Portable fans, Oven, Baking sheet, Fire extin...
3        [Fire extinguisher, Clothing storage: closet, ...
4        [Oven, Rice maker, Laundromat nearby, Luggage ...
                               ...
22303    [Air conditioning, Carbon monoxide alarm, Wifi...
22304    [Air conditioning, Carbon monoxide alarm, Wash...
22305    [Air conditioning, Carbon monoxide alarm, Wash...
22306    [Oven, Gym, Blender, Dedicated workspace, Dini...
22307    [Air conditioning, Carbon monoxide alarm, Wash...
Name: amenities, Length: 22308, dtype: object