## 변수 간 관계 분석

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import math
import platform

df = pd.read_csv(r'C:\Users\컴퓨터\Documents\[부캠][basic] 심화프로젝트\2025_Airbnb_NYC_listings.csv') #----- 자기 경로 설정!!
df_cleaned = pd.read_csv(r'C:\Users\컴퓨터\Documents\data-analysis-project-BBB\data\first_clean_data.csv')

In [2]:
# ============================================================
# 라이브러리 Import
# ============================================================

# 데이터 처리 및 분석
import os
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import warnings

# 시각화
import matplotlib.pyplot as plt
import seaborn as sns

# 통계 분석
from scipy import stats
from scipy.stats import shapiro, levene, ttest_ind, chi2_contingency, f_oneway
from scipy.stats import mannwhitneyu, fisher_exact, kruskal
from scipy.stats import skew, kurtosis
from statsmodels.stats.multicomp import pairwise_tukeyhsd, MultiComparison
import pingouin as pg
import scikit_posthocs as sp

# 머신러닝
from sklearn.preprocessing import MinMaxScaler

# 출력 설정
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# 한글 폰트 설정
import platform
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':  # macOS
    plt.rcParams['font.family'] = 'AppleGothic'
else:  # Linux
    plt.rcParams['font.family'] = 'NanumGothic'

plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.figsize'] = (12, 6)

# 참고: seed 고정으로 팀원 간 동일한 결과 재현 가능
np.random.seed(42)

print("="*60)
print("라이브러리 로드 완료!")
print("한글 폰트 설정 완료!")
print("="*60)

============================================================
라이브러리 로드 완료!
한글 폰트 설정 완료!
============================================================

# 머신러닝 전용 df 전처리

In [3]:
df_machine = df_cleaned.copy()
df_machine.head()

,Unnamed: 0,id,name,description,host_id,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bedrooms,beds,amenities,price,availability_365,number_of_reviews,number_of_reviews_ltm,estimated_occupancy_l365d,estimated_revenue_l365d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,log_price
0,0,36121,Lg Rm in Historic Prospect Heights,Cozy space share in the heart of a great neigh...,62165,2009-12-11,-1.0,-1.0,87.0,False,Prospect Heights,Brooklyn,40.673760,-73.966110,Private room in rental unit,Private room,1,1.0,1.0,"[""Refrigerator"", ""Dishes and silverware"", ""Wif...",200,362,9,0,0,0.0,4.88,5.00,4.80,5.00,5.00,5.00,5.00,1,0,1,0,0.05,5.303305
1,1,36647,"1 Bedroom & your own Bathroom, Elevator Apartment",Private bedroom with your own bathroom in a 2 ...,157798,2010-07-04,-1.0,-1.0,100.0,False,East Harlem,Manhattan,40.792454,-73.940742,Private room in condo,Private room,2,1.0,1.0,"[""Oven"", ""Blender"", ""Luggage dropoff allowed"",...",82,204,102,0,0,0.0,4.77,4.82,4.76,4.88,4.90,4.38,4.71,1,0,1,0,0.58,4.418841
2,2,38663,Luxury Brownstone in Boerum Hill,"Beautiful, large home in great hipster neighbo...",165789,2010-07-13,3.0,100.0,40.0,False,Boerum Hill,Brooklyn,40.684420,-73.980680,Private room in home,Private room,2,5.0,5.0,"[""Portable fans"", ""Oven"", ""Baking sheet"", ""Fir...",765,326,43,0,0,0.0,4.70,4.83,4.52,4.88,4.88,4.86,4.62,1,0,1,0,0.28,6.641182
3,3,38833,Spectacular West Harlem Garden Apt,This is a very large and unique space. An inc...,166532,2010-07-14,4.0,100.0,97.0,True,Harlem,Manhattan,40.818058,-73.946671,Entire home,Entire home/apt,2,1.0,1.0,"[""Fire extinguisher"", ""Clothing storage: close...",139,25,241,42,255,35445.0,4.85,4.87,4.50,4.96,4.96,4.79,4.82,1,1,0,0,1.36,4.941642
4,4,39282,“Work-from-home” from OUR home.,*Monthly Discount will automatically apply <br...,168525,2010-07-16,4.0,100.0,100.0,True,Williamsburg,Brooklyn,40.710651,-73.950874,Private room in rental unit,Private room,2,1.0,1.0,"[""Oven"", ""Rice maker"", ""Laundromat nearby"", ""L...",130,38,274,12,154,20020.0,4.82,4.83,4.61,4.94,4.88,4.85,4.78,2,0,2,0,1.54,4.875197

# 컬럼 드랍

In [4]:
drop_cols = ['name', 'description', 'neighbourhood_cleansed', 'number_of_reviews', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value','estimated_occupancy_l365d','estimated_revenue_l365d','calculated_host_listings_count_shared_rooms','reviews_per_month']
df_machine.drop(columns = drop_cols)

,Unnamed: 0,id,host_id,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bedrooms,beds,amenities,price,availability_365,number_of_reviews_ltm,review_scores_rating,review_scores_accuracy,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,log_price
0,0,36121,62165,2009-12-11,-1.0,-1.0,87.0,False,Brooklyn,40.673760,-73.966110,Private room in rental unit,Private room,1,1.0,1.0,"[""Refrigerator"", ""Dishes and silverware"", ""Wif...",200,362,0,4.88,5.00,1,0,1,5.303305
1,1,36647,157798,2010-07-04,-1.0,-1.0,100.0,False,Manhattan,40.792454,-73.940742,Private room in condo,Private room,2,1.0,1.0,"[""Oven"", ""Blender"", ""Luggage dropoff allowed"",...",82,204,0,4.77,4.82,1,0,1,4.418841
2,2,38663,165789,2010-07-13,3.0,100.0,40.0,False,Brooklyn,40.684420,-73.980680,Private room in home,Private room,2,5.0,5.0,"[""Portable fans"", ""Oven"", ""Baking sheet"", ""Fir...",765,326,0,4.70,4.83,1,0,1,6.641182
3,3,38833,166532,2010-07-14,4.0,100.0,97.0,True,Manhattan,40.818058,-73.946671,Entire home,Entire home/apt,2,1.0,1.0,"[""Fire extinguisher"", ""Clothing storage: close...",139,25,42,4.85,4.87,1,1,0,4.941642
4,4,39282,168525,2010-07-16,4.0,100.0,100.0,True,Brooklyn,40.710651,-73.950874,Private room in rental unit,Private room,2,1.0,1.0,"[""Oven"", ""Rice maker"", ""Laundromat nearby"", ""L...",130,38,12,4.82,4.83,2,0,2,4.875197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22243,37429,1366333532374850165,40019013,2015-07-30,-1.0,-1.0,87.0,False,Manhattan,40.813794,-73.952399,Private room in rental unit,Private room,1,1.0,1.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ...",72,358,0,NaN,NaN,1,0,1,4.290459
22244,37430,1366717321390111215,483056418,2022-10-10,4.0,100.0,80.0,True,Brooklyn,40.685500,-73.919510,Private room in rental unit,Private room,2,1.0,0.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ...",58,363,0,NaN,NaN,24,0,24,4.077537
22245,37431,1366721904709517353,30283594,2015-03-30,4.0,94.0,99.0,False,Manhattan,40.745290,-73.979380,Entire rental unit,Entire home/apt,5,2.0,3.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ...",299,99,0,NaN,NaN,48,48,0,5.703782
22246,37432,1366722692755341871,407304997,2021-06-15,4.0,89.0,100.0,False,Manhattan,40.757133,-73.983124,Entire rental unit,Entire home/apt,4,2.0,2.0,"[""Oven"", ""Gym"", ""Blender"", ""Dedicated workspac...",200,365,0,NaN,NaN,25,25,0,5.303305
22247,37433,1366723228243064949,483056418,2022-10-10,4.0,100.0,80.0,True,Brooklyn,40.685500,-73.919510,Private room in rental unit,Private room,2,1.0,0.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ...",58,363,0,NaN,NaN,24,0,24,4.077537

# 리뷰 수, 평점 null값 드롭

In [8]:
df_machine = df_machine.dropna(subset='review_scores_rating')

In [9]:
df_machine['review_scores_rating'].isna().sum()

np.int64(0)

In [10]:
df_machine

,Unnamed: 0,id,name,description,host_id,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bedrooms,beds,amenities,price,availability_365,number_of_reviews,number_of_reviews_ltm,estimated_occupancy_l365d,estimated_revenue_l365d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,log_price
0,0,36121,Lg Rm in Historic Prospect Heights,Cozy space share in the heart of a great neigh...,62165,2009-12-11,-1.0,-1.0,87.0,False,Prospect Heights,Brooklyn,40.673760,-73.966110,Private room in rental unit,Private room,1,1.0,1.0,"[""Refrigerator"", ""Dishes and silverware"", ""Wif...",200,362,9,0,0,0.0,4.88,5.00,4.80,5.00,5.00,5.00,5.00,1,0,1,0,0.05,5.303305
1,1,36647,"1 Bedroom & your own Bathroom, Elevator Apartment",Private bedroom with your own bathroom in a 2 ...,157798,2010-07-04,-1.0,-1.0,100.0,False,East Harlem,Manhattan,40.792454,-73.940742,Private room in condo,Private room,2,1.0,1.0,"[""Oven"", ""Blender"", ""Luggage dropoff allowed"",...",82,204,102,0,0,0.0,4.77,4.82,4.76,4.88,4.90,4.38,4.71,1,0,1,0,0.58,4.418841
2,2,38663,Luxury Brownstone in Boerum Hill,"Beautiful, large home in great hipster neighbo...",165789,2010-07-13,3.0,100.0,40.0,False,Boerum Hill,Brooklyn,40.684420,-73.980680,Private room in home,Private room,2,5.0,5.0,"[""Portable fans"", ""Oven"", ""Baking sheet"", ""Fir...",765,326,43,0,0,0.0,4.70,4.83,4.52,4.88,4.88,4.86,4.62,1,0,1,0,0.28,6.641182
3,3,38833,Spectacular West Harlem Garden Apt,This is a very large and unique space. An inc...,166532,2010-07-14,4.0,100.0,97.0,True,Harlem,Manhattan,40.818058,-73.946671,Entire home,Entire home/apt,2,1.0,1.0,"[""Fire extinguisher"", ""Clothing storage: close...",139,25,241,42,255,35445.0,4.85,4.87,4.50,4.96,4.96,4.79,4.82,1,1,0,0,1.36,4.941642
4,4,39282,“Work-from-home” from OUR home.,*Monthly Discount will automatically apply <br...,168525,2010-07-16,4.0,100.0,100.0,True,Williamsburg,Brooklyn,40.710651,-73.950874,Private room in rental unit,Private room,2,1.0,1.0,"[""Oven"", ""Rice maker"", ""Laundromat nearby"", ""L...",130,38,274,12,154,20020.0,4.82,4.83,4.61,4.94,4.88,4.85,4.78,2,0,2,0,1.54,4.875197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21609,36779,1339828135232751364,Cozy Retreat NYC Apartment Fit for Families!,"Welcome to our modern and cozy 2-bedroom, 1-ba...",516682555,2023-05-26,4.0,100.0,93.0,False,East Village,Manhattan,40.730390,-73.988940,Entire rental unit,Entire home/apt,4,2.0,2.0,"[""Oven"", ""First aid kit"", ""Free washer \u2013 ...",332,301,4,4,51,16932.0,5.00,5.00,5.00,5.00,5.00,4.75,5.00,2,2,0,0,4.00,5.808142
21611,36781,1339838938668106394,RARE Luxurious Apartment 1 Block From Time Squ...,Stay in the center of it all at this stylish 2...,567273633,2024-03-15,4.0,95.0,100.0,False,Midtown,Manhattan,40.756340,-73.982220,Entire rental unit,Entire home/apt,6,2.0,3.0,"[""Oven"", ""First aid kit"", ""Dining table"", ""Coo...",467,286,3,3,38,17746.0,5.00,5.00,5.00,5.00,5.00,5.00,4.67,2,2,0,0,3.00,6.148468
21624,36794,1339852338095933370,Spacious 3BR Family Haven in Lower Manhattan,Welcome to our spacious and family-friendly 3-...,567273633,2024-03-15,4.0,95.0,100.0,False,Financial District,Manhattan,40.708020,-74.001450,Entire rental unit,Entire home/apt,9,3.0,5.0,"[""Oven"", ""First aid kit"", ""Dining table"", ""Ext...",465,319,2,2,26,12090.0,5.00,5.00,5.00,5.00,5.00,5.00,5.00,2,2,0,0,2.00,6.144186
21647,36817,1348032300167221882,Upscale Comfort: Stylish 2BR in the Heart of NYC,Experience the best of Midtown Manhattan at th...,552857810,2023-12-27,4.0,100.0,99.0,True,Hell's Kitchen,Manhattan,40.753980,-73.995330,Entire rental unit,Entire home/apt,5,2.0,3.0,"[""Stainless steel electric stove"", ""Fire extin...",344,290,2,2,26,8944.0,5.00,5.00,5.00,5.00,5.00,5.00,5.00,1,1,0,0,2.00,5.843544
21649,36819,1348081441771732943,NYC Skyline Penthouse 2Br/2Bath,Welcome to your dream stay in the heart of New...,676667930,2025-02-02,4.0,100.0,100.0,False,Hell's Kitchen,Manhattan,40.757180,-73.990510,Entire rental unit,Entire home/apt,5,2.0,2.0,"[""Baking sheet"", ""Oven"", ""Dedicated workspace""...",942,325,2,2,26,24492.0,5.00,5.00,5.00,5.00,5.00,5.00,5.00,1,1,0,0,2.00,6.849066